# Generated by Django 2.0.6 on 2019-07-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('features', models.CharField(default='', max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=225, null=True, unique=True)),
                ('image', models.CharField(default='', max_length=225, null=True)),
                ('price', models.CharField(default='', max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurifierBrands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brands', models.CharField(max_length=225, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='modals',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_panel.PurifierBrands'),
        ),
        migrations.AddField(
            model_name='features',
            name='modal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_panel.Modals'),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='modal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_panel.Modals'),
        ),
    ]
