# Generated by Django 2.0.6 on 2019-07-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('name', models.CharField(default='', max_length=225)),
                ('email', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=225)),
                ('mobile', models.CharField(default='', max_length=225)),
                ('image', models.CharField(default='', max_length=225, null=True)),
                ('gender', models.CharField(default='', max_length=225, null=True)),
                ('address', models.CharField(default='', max_length=225, null=True)),
                ('otp', models.CharField(default='', max_length=225, null=True)),
                ('active', models.CharField(default='', max_length=225)),
                ('verify_link', models.CharField(default='', max_length=225, null=True)),
                ('auth_token', models.CharField(default='', max_length=225, null=True)),
            ],
        ),
    ]
